name: backend-test-service

services:
  node-server:
    build:
      context: .
    container_name: node-server
    volumes:
      - .:/home/node/app
    working_dir: /home/node/app
    command: npm run api
    ports:
      - "3333:3333"
    network_mode: "host"
    depends_on:
      - pg

  pg:
    image: bitnami/postgresql:latest
    container_name: pg
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=llmservice
    network_mode: "host"
